import { red_black_tree_insert } from "./red-black-tree"

test('red_black_tree_insert', () => {
    let root = red_black_tree_insert(null, 25)
    root = red_black_tree_insert(root, 5)
    root = red_black_tree_insert(root, 40)
    expect(root.color).toBe("b")
    expect(root.left.color).toBe("r")
    expect(root.right.color).toBe("r")

    root = red_black_tree_insert(root, 15)
    root = red_black_tree_insert(root, 30)
    root = red_black_tree_insert(root, 50)
    root = red_black_tree_insert(root, 10)

    expect(root.color).toBe("b")
    expect(root.left.color).toBe("b")
    expect(root.right.color).toBe("b")
    expect(root.left.left.color).toBe("r")
    expect(root.left.right.color).toBe("r")
    expect(root.right.left.color).toBe("r")
    expect(root.right.right.color).toBe("r")

    root = red_black_tree_insert(root, 20)
    root = red_black_tree_insert(root, 35)
    expect(root.color).toBe("b")
    expect(root.left.color).toBe("r")
    expect(root.right.color).toBe("r")
    expect(root.left.left.color).toBe("b")
    expect(root.left.right.color).toBe("b")
    expect(root.right.left.color).toBe("b")
    expect(root.right.right.color).toBe("b")
    expect(root.left.right.left.color).toBe("r")
    expect(root.right.left.left.color).toBe("r")

    root = red_black_tree_insert(root, 7)

})



test('red_black_tree_insert 2', () => {
    let root = red_black_tree_insert(null, 12)
    root = red_black_tree_insert(root, 8)
    root = red_black_tree_insert(root, 3)
    expect(root.color).toBe("b")
    expect(root.key).toBe(8)
    expect(root.left.color).toBe("r")
    expect(root.left.key).toBe(3)
    expect(root.right.color).toBe("r")
    expect(root.right.key).toBe(12)

    root = red_black_tree_insert(root, 19)
    expect(root.color).toBe("b")
    expect(root.key).toBe(8)
    expect(root.left.color).toBe("b")
    expect(root.left.key).toBe(3)
    expect(root.right.color).toBe("b")
    expect(root.right.key).toBe(19)
    expect(root.right.left.color).toBe("r")
    expect(root.right.left.key).toBe(12)

    root = red_black_tree_insert(root, 17)
    expect(root.color).toBe("b")
    expect(root.key).toBe(8)
    expect(root.left.color).toBe("b")
    expect(root.left.key).toBe(3)
    expect(root.right.color).toBe("b")
    expect(root.right.key).toBe(17)
    expect(root.right.left.color).toBe("r")
    expect(root.right.left.key).toBe(12)
    expect(root.right.right.color).toBe("r")
    expect(root.right.right.key).toBe(19)

    root = red_black_tree_insert(root, 14)
    expect(root.color).toBe("b")
    expect(root.key).toBe(17)
    expect(root.left.color).toBe("r")
    expect(root.left.key).toBe(8)
    expect(root.right.color).toBe("b")
    expect(root.right.key).toBe(19)
    expect(root.left.left.color).toBe("b")
    expect(root.left.left.key).toBe(3)
    expect(root.left.right.color).toBe("b")
    expect(root.left.right.key).toBe(14)
    expect(root.left.right.left.color).toBe("r")
    expect(root.left.right.left.key).toBe(12)
})
